export const SET_COMMUNITY_DETAILS = 'SET_COMMUNITY_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const START_LOADING = 'START_LOADING';
export const CLOSE_LOADING = 'CLOSE_LOADING';
